name: code_gen_tester
version: 0.0.1
environment:
    sdk: ^2.5.0
dependencies:
    source_gen: ^0.9.5
    build: ^1.2.2
    analyzer: ">=0.39.8 <0.41.0"
    test: ^1.14.3
    dart_style: ^1.3.6
    pedantic: ^1.9.0
    build_runner: ^1.9.0
    build_test: ^1.0.0
